name: Snap

on:
  push:
    branches: [ubuntu24]
    tags: ['*']
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
    - uses: jlumbroso/free-disk-space@3e0187054f9c4bc1f55a743792872df36b2d88e0
      with:
        tool-cache: true
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: "recursive"
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v4
      with:
        name: snap
        path: ${{ github.workspace }}/*.snap
        retention-days: 5
    - name: Publish to edge
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/ubuntu24'
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
    - name: Publish to candidate
      if: startsWith(github.ref, 'refs/tags/')
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: candidate
